In [1]:
#Who are the Dutch (or European) aviation clients and why?

In [ ]:
details passenger data of CAA.UK 
EXCEL SOURCE 
https://www.caa.co.uk/Data-and-analysis/UK-aviation-market/Consumer-research/Departing-passenger-survey/2018-Passenger-survey-report/

In [ ]:
General ducth flight info: 
https://opendata.cbs.nl/statline/#/CBS/nl/dataset/37478hvv/table?dl=18AB7
    
https://www.eerlijkovervliegen.nl/feiten/vliegen-en-economie/

In [ ]:
https://www.spiegel.de/wirtschaft/unternehmen/gruenen-waehler-halten-rekord-bei-flugreisen-a-1002376.html

In [4]:
#centraal bureau voor toerisme

In [49]:
#https://opendata.cbs.nl/statline/#/CBS/nl/dataset/84363NED/table?ts=1572538836120
import numpy as np
import pandas as pd
nlvakanties = pd.read_csv("csv/cbs_vakantie.csv", sep = ';')
nlvakanties

,Bestemming en seizoen,Vakantiekenmerken,Perioden,Deelname/Totaal Nederlanders (x 1 000),Vakanties/Totaal (x 1 000),Vakantiedagen/Totaal (mln ),Overnachtingen/Totaal (mln ),Uitgaven/Totaal (mln euro)
0,Totaal vakanties,Totaal vakanties,2017*,14084,41252,364.9,323.6,20637
1,Totaal vakanties,Totaal vakanties,2018*,14124,40854,366.9,326.1,21338
2,Totaal vakanties,"Accommodatie: hotel, pension, B&B",2017*,7642,14565,101.3,86.8,9900
3,Totaal vakanties,"Accommodatie: hotel, pension, B&B",2018*,7770,14517,104.1,89.6,10300
4,Totaal vakanties,"Accommodatie: vakantiehuis, stacaravan",2017*,6341,11740,98.8,87.1,3555
...,...,...,...,...,...,...,...,...
375,Winterseizoen,Vervoerwijze: vliegtuig,2018*,3303,4381,51.6,47.2,4716
376,Winterseizoen,Vervoerwijze: trein,2017*,665,844,3.5,2.7,218
377,Winterseizoen,Vervoerwijze: trein,2018*,648,825,3.6,2.8,270
378,Winterseizoen,Vervoerwijze: overige,2017*,718,905,6.1,5.2,291
379,Winterseizoen,Vervoerwijze: overige,2018*,656,851,5.9,5.0,324

In [51]:
import numpy as np 
pd.options.display.max_rows = 200
vakangties_pt = nlvakanties.pivot_table(values=['Deelname/Totaal Nederlanders (x 1 000)'],
                                         #'Vakanties/Totaal (x 1 000)',
                                         #'Vakantiedagen/Totaal (mln )',
                                         #'Overnachtingen/Totaal (mln )', 
                                         #'Uitgaven/Totaal (mln euro)'], 
                     index=['Vakantiekenmerken'],
                     columns=['Bestemming en seizoen'], 
                     aggfunc=np.sum)
                     #fill_value=0)
vakangties_pt["Vakantiekenmerken"]= vakangties_pt.index
vakanties = vakangties_pt.reset_index(drop=True)
vakanties

                      Deelname/Totaal Nederlanders (x 1 000)  \
Bestemming en seizoen                       Totaal vakanties
0                                               2004    2065
1                                               7642    7770
2                                               3064    3104
3                                                965     893
4                                               4017    3942
5                                               6341    6457
6                                               6023    6298
7                                               9129    9675
8                                               1676    1472
9                                               1681    1709
10                                              4715    3722
11                                              3850    3921
12                                              3080    3309
13                                              1362    1547
14                                              3636    3775
15                                              6146    5820
16                                              6239    6259
17                                              2322    2456
18                                              4644    4271
19                                              1865    1943
20                                              1681    1709
21                                              4544    3610
22                                              2015    1946
23                                              3331    4445
24                                              1463    1360
25                                              1495    1618
26                                              3438    3449
27                                              3922    3914
28                                             14084   14124
29                                              4897    4859
30                                              7552    7511
31                                             12922   12961
32                                              8093    8262
33                                              6001    6025
34                                             11152   11210
35                                              1715    1598
36                                              1223    1221
37                                              6351    6490

                                                     \
Bestemming en seizoen Vakantiebestemming: Nederland
0                                       260     273
1                                      3330    3217
2                                      1694    1756
3                                       527     494
4                                      1489    1500
5                                      4462    4477
6                                       390     389
7                                      6224    6761
8                                         .       .
9                                      1177    1181
10                                     3132    2286
11                                        .       .
12                                      247     301
13                                      608     626
14                                     1649    1701
15                                     3613    3339
16                                     3903    4004
17                                      941    1012
18                                     2396    2128
19                                      741     831
20                                     1177    1181
21                                     2838    2052
22                                     1029    1039
23                                     1978    2853
24                                      991     819
25                                        .       .
26                                     1086     997
27                                      904    1043
28                                     8786    8855
29                                      870     930
30                                     5734    5596
31                                     5401    5423
32                                     4113    4223
33                                     1376    1316
34                                     8093    8101
35                                      791     739
36                                      767     761
37                                        .       .

                                                                        \
Bestemming en seizoen Vakantiebestemming: buitenland     Winterseizoen
0                                       1794    1836       988    1005
1                                       5936    6059      4950    4670
2                                       1925    1893       517     530
3                                        467     431       460     397
4                                       2793    2767      2160    2054
5                                       2733    2889      3551    3511
6                                       5805    6065      3283    3189
7                                       5162    5431      5193    5439
8                                       1574    1389       832     722
9                                        597     632       987     947
10                                      2120    1806      2363    1758
11                                      3762    3840      1801    1724
12                                      2892    3066      1764    1715
13                                       877    1055       823     892
14                                      2531    2627      2093    2007
15                                      4342    4136      3813    3509
16                                      4487    4420      3735    3597
17                                      1736    1814      1304    1308
18                                      2934    2732      2491    2256
19                                      1253    1245       884     934
20                                       597     632       987     947
21                                      2205    1845      2610    2101
22                                      1148    1052       774     660
23                                      1600    2134      1637    1957
24                                       540     584       794     775
25                                      1418    1554       550     457
26                                      2721    2740      2138    2135
27                                      3197    3110      1167    1146
28                                     10991   10942      9534    9233
29                                      4133    4046      1149    1155
30                                      3177    3225      5266    5153
31                                     10302   10293      6578    6375
32                                      5033    5155      4519    4289
33                                      4918    4964      2076    1996
34                                      6393    6435      6924    6665
35                                      1051    1006       718     656
36                                       533     544       665     648
37                                      6351    6490      3504    3303

                                         \
Bestemming en seizoen      Zomerseizoen
0                          1203    1218
1                          5200    5594
2                          2954    2965
3                           624     577
4                          2521    2604
5                          4479    4607
6                          4209    4617
7                          7036    7669
8                          1032     932
9                          1330    1382
10                         3229    2552
11                         2567    2763
12                         1904    2199
13                          801     999
14                         2384    2599
15                         5119    4856
16                         5504    5645
17                         1554    1679
18                         3089    2842
19                         1166    1208
20                         1330    1382
21                         2668    2095
22                         1455    1476
23                         2100    3209
24                          765     672
25                         1058    1276
26                         1899    1931
27                         3135    3204
28                        12819   12946
29                         4132    4166
30                         4569    4556
31                        11582   11683
32                         5305    5723
33                         4595    4749
34                         9280    9431
35                         1168    1143
36                          713     706
37                         4541    4812

                                              Vakantiekenmerken
Bestemming en seizoen
0                                     Accommodatie: appartement
1                             Accommodatie: hotel, pension, B&B
2                                 Accommodatie: kampeerverblijf
3                                Accommodatie: overig, onbekend
4                              Accommodatie: particulier (alle)
5                        Accommodatie: vakantiehuis, stacaravan
6                          Organisatie: accommodatie en vervoer
7                              Organisatie: alleen accommodatie
8                                   Organisatie: alleen vervoer
9                         Organisatie: eigen recreatieve accom.
10                                 Organisatie: op de bonnefooi
11                                      Organisatie: pakketreis
12                              Organisatie: samengestelde reis
13                               Reisgezelschap: alleenreizende
14                             Reisgezelschap: familie, anderen
15                         Reisgezelschap: paar zonder kinderen
16                     Reisgezelschap: volwassene en kind(eren)
17                     Reisgezelschap: vrienden, bekenden, e.a.
18                                       Soort vakantie: actief
19                                      Soort vakantie: cultuur
20                     Soort vakantie: eigen recreatieve accom.
21                      Soort vakantie: familie, vrienden, e.d.
22                                       Soort vakantie: natuur
23                             Soort vakantie: overig, onbekend
24                                    Soort vakantie: recreatie
25                                     Soort vakantie: rondreis
26                                       Soort vakantie: steden
27                                       Soort vakantie: strand
28                                             Totaal vakanties
29                               Vakantieduur: 16 of meer dagen
30                           Vakantieduur: 2 tot 5 dagen (kort)
31                         Vakantieduur: 5 of meer dagen (lang)
32                                  Vakantieduur: 5 tot 9 dagen
33                                 Vakantieduur: 9 tot 16 dagen
34                                           Vervoerwijze: auto
35                                       Vervoerwijze: overige
36                                          Vervoerwijze: trein
37                                      Vervoerwijze: vliegtuig

In [3]:
vliegen = nlvakanties[nlvakanties["Vakantiekenmerken"]=='Vervoerwijze: vliegtuig']
auto = nlvakanties[nlvakanties["Vakantiekenmerken"]=='Vervoerwijze: auto']
overig = nlvakanties[nlvakanties["Vakantiekenmerken"]=='Vervoerwijze: overige']
trein = nlvakanties[nlvakanties["Vakantiekenmerken"]=='Vervoerwijze: trein']
vliegen.transpose()

,70,71,146,147,222,223,298,299,374,375
Bestemming en seizoen,Totaal vakanties,Totaal vakanties,Vakantiebestemming: Nederland,Vakantiebestemming: Nederland,Vakantiebestemming: buitenland,Vakantiebestemming: buitenland,Zomerseizoen,Zomerseizoen,Winterseizoen,Winterseizoen
Vakantiekenmerken,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig,Vervoerwijze: vliegtuig
Perioden,2017*,2018*,2017*,2018*,2017*,2018*,2017*,2018*,2017*,2018*
Deelname/Totaal Nederlanders (x 1 000),6351,6490,.,.,6351,6490,4541,4812,3504,3303
Vakanties/Totaal (x 1 000),10114,10322,.,.,10098,10297,5548,5942,4566,4381
Vakantiedagen/Totaal (mln ),125.5,127.5,.,.,125.4,127.2,72.4,75.9,53.0,51.6
Overnachtingen/Totaal (mln ),115.4,117.2,.,.,115.3,116.9,66.9,70.0,48.5,47.2
Uitgaven/Totaal (mln euro),11203,11455,.,.,11192,11443,6321,6738,4882,4716

In [4]:
vliegen.transpose()
vlieg_columns = [70, 71, 146, 147, 222, 223, 298, 299, 374, 375]
vlieg_columns_new = ["Totaal vakanties",'Totaal vakanties',  ]
vliegen = vliegen.transpose()
vliegen['Totaal vakanties']= vliegen[70]+ vliegen[71]
vliegen['Zomerseizoen']= vliegen[298]+ vliegen[299]
vliegen['Winterseizoen']= vliegen[374]+ vliegen[375]
vliegen_basis = vliegen.drop([70,71,146,147,222,223,298, 299,374,375], axis=1)[3:]
vliegen_basis

,Totaal vakanties,Zomerseizoen,Winterseizoen
Deelname/Totaal Nederlanders (x 1 000),6351 6490,4541 4812,3504 3303
Vakanties/Totaal (x 1 000),10114 10322,5548 5942,4566 4381
Vakantiedagen/Totaal (mln ),125.5 127.5,72.4 75.9,53.0 51.6
Overnachtingen/Totaal (mln ),115.4 117.2,66.9 70.0,48.5 47.2
Uitgaven/Totaal (mln euro),11203 11455,6321 6738,4882 4716

In [7]:
trein = nlvakanties[nlvakanties["Vakantiekenmerken"]=='Vervoerwijze: trein']
trein = trein.transpose()
trein['Totaal vakanties']= trein[72]+ trein[73]
trein['binnenland']= trein[148]+ trein[149]
trein['buitenalnd']= trein[224]+ trein[225]
trein['Zomerseizoen']= trein[300]+ trein[301]
trein['Winterseizoen']= trein[376]+ trein[377]
trein_basis = trein.drop([72,73, 148, 149, 224, 225, 300, 301,376,377], axis=1)[3:]
trein_basis

,Totaal vakanties,binnenland,buitenalnd,Zomerseizoen,Winterseizoen
Deelname/Totaal Nederlanders (x 1 000),1223 1221,767 761,533 544,713 706,665 648
Vakanties/Totaal (x 1 000),1742 1705,1112 1059,630 646,899 880,844 825
Vakantiedagen/Totaal (mln ),8.8 9.0,5.0 4.5,3.9 4.5,5.3 5.4,3.5 3.6
Overnachtingen/Totaal (mln ),7.1 7.3,3.9 3.4,3.2 3.9,4.4 4.5,2.7 2.8
Uitgaven/Totaal (mln euro),558 632,215 245,344 387,340 362,218 270

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#sns.barplot(x=x, y=y, palette="vlag", ax=ax2)

plt.figure(figsize=(9, 9))
ax = sns.barplot(x= "Total", y= "Line Name", palette="vlag_r", data=base_occupation)
#ax.invert_yaxis()

NameError: name 'base_occupation' is not defined

In [40]:
auto

,Bestemming en seizoen,Vakantiekenmerken,Perioden,Deelname/Totaal Nederlanders (x 1 000),Vakanties/Totaal (x 1 000),Vakantiedagen/Totaal (mln ),Overnachtingen/Totaal (mln ),Uitgaven/Totaal (mln euro)
68,Totaal vakanties,Vervoerwijze: auto,2017*,11152,26920,208.9,181.9,7795
69,Totaal vakanties,Vervoerwijze: auto,2018*,11210,26390,209.3,182.9,8085
144,Vakantiebestemming: Nederland,Vervoerwijze: auto,2017*,8093,16865,105.2,88.4,3054
145,Vakantiebestemming: Nederland,Vervoerwijze: auto,2018*,8101,16518,108.1,91.6,3417
220,Vakantiebestemming: buitenland,Vervoerwijze: auto,2017*,6393,10055,103.6,93.6,4741
221,Vakantiebestemming: buitenland,Vervoerwijze: auto,2018*,6435,9873,101.1,91.3,4669
296,Zomerseizoen,Vervoerwijze: auto,2017*,9280,15531,143.9,128.3,5106
297,Zomerseizoen,Vervoerwijze: auto,2018*,9431,15553,147.0,131.5,5368
372,Winterseizoen,Vervoerwijze: auto,2017*,6924,11389,65.0,53.6,2689
373,Winterseizoen,Vervoerwijze: auto,2018*,6665,10838,62.2,51.4,2718

In [34]:
numeriek = nlvakanties[['Vakantiekenmerken', 'Deelname/Totaal Nederlanders (x 1 000)', 
            'Vakanties/Totaal (x 1 000)',
            'Overnachtingen/Totaal (mln )', 
            'Uitgaven/Totaal (mln euro)']]
numeriek.head(2)

,Vakantiekenmerken,Deelname/Totaal Nederlanders (x 1 000),Vakanties/Totaal (x 1 000),Overnachtingen/Totaal (mln ),Uitgaven/Totaal (mln euro)
0,Totaal vakanties,14084,41252,323.6,20637
1,Totaal vakanties,14124,40854,326.1,21338

In [29]:
numeriek.groupby(['Vakantiekenmerken']).sum()

,Deelname/Totaal Nederlanders (x 1 000),Vakanties/Totaal (x 1 000),Overnachtingen/Totaal (mln ),Uitgaven/Totaal (mln euro)
Vakantiekenmerken,,,,
Accommodatie: appartement,2004 2065 260 273 1794 18...,2451 2428 269 290 2182 21...,22.5 22.5 1.3 1.6 21.3 21...,1762 1855 75 101 1687 17...
"Accommodatie: hotel, pension, B&B",7642 7770 3330 3217 5936 60...,14565 14517 5077 4889 9488 96...,86.8 89.6 11.9 12.5 74.9 77...,9900 10300 1047 1205 8852 90...
Accommodatie: kampeerverblijf,3064 3104 1694 1756 1925 18...,5358 5226 2900 2882 2458 23...,66.8 69.5 24.5 27.5 42.2 41...,2172 2143 487 546 1684 15...
"Accommodatie: overig, onbekend",965 893 527 494 467 4...,1412 1310 886 806 526 5...,10.0 9.0 5.1 3.7 4.9 5...,752 768 137 121 615 6...
Accommodatie: particulier (alle),4017 3942 1489 1500 2793 27...,5726 5677 2001 1988 3725 36...,50.5 47.6 9.7 9.6 40.8 38...,2497 2517 324 366 2173 21...
"Accommodatie: vakantiehuis, stacaravan",6341 6457 4462 4477 2733 28...,11740 11696 8035 7882 3705 38...,87.1 87.8 46.6 47.1 40.4 40...,3555 3754 1416 1563 2139 21...
Organisatie: accommodatie en vervoer,6023 6298 390 389 5805 60...,9437 9822 452 472 8985 93...,86.3 91.3 2.0 1.9 84.3 89...,9973 10581 136 174 9837 104...
Organisatie: alleen accommodatie,9129 9675 6224 6761 5162 54...,17348 18871 10218 11263 7130 76...,106.7 119.3 44.6 52.3 62.2 67...,5898 6709 2190 2714 3708 39...
Organisatie: alleen vervoer,1676 1472 . . 1574 13...,2095 1869 . . 1979 17...,28.2 23.5 . . 27.6 22...,1815 1575 . . 1789 15...
Organisatie: eigen recreatieve accom.,1681 1709 1177 1181 597 6...,5232 4916 3943 3715 1290 12...,47.2 47.8 29.1 31.1 18.1 16...,895 923 369 396 526 5...
Organisatie: op de bonnefooi,4715 3722 3132 2286 2120 18...,7140 5375 4440 3144 2700 22...,55.2 44.1 23.0 16.0 32.3 28...,2056 1550 765 578 1291 9...
Organisatie: pakketreis,3850 3921 . . 3762 38...,4942 5123 . . 4787 49...,48.1 48.4 . . 47.4 48...,5734 5984 . . 5671 59...
Organisatie: samengestelde reis,3080 3309 247 301 2892 30...,4495 4699 297 346 4197 43...,38.1 42.9 1.3 1.5 36.9 41...,4240 4597 74 122 4166 44...
Reisgezelschap: alleenreizende,1362 1547 608 626 877 10...,2297 2874 1001 1276 1296 15...,18.1 22.4 4.3 5.7 13.7 16...,1459 1993 173 265 1287 17...
"Reisgezelschap: familie, anderen",3636 3775 1649 1701 2531 26...,5657 5784 2287 2315 3369 34...,39.1 40.3 9.9 10.6 29.2 29...,3076 3092 454 503 2622 25...
Reisgezelschap: paar zonder kinderen,6146 5820 3613 3339 4342 41...,15375 13899 7451 6674 7924 72...,134.1 123.2 43.7 40.3 90.4 83...,8815 8132 1511 1558 7304 65...
Reisgezelschap: volwassene en kind(eren),6239 6259 3903 4004 4487 44...,14240 14392 7132 7137 7108 72...,112.1 117.7 37.1 41.0 75.0 76...,5258 5659 1111 1225 4148 44...
"Reisgezelschap: vrienden, bekenden, e.a.",2322 2456 941 1012 1736 18...,3684 3904 1296 1336 2388 25...,20.4 22.4 4.1 4.4 16.2 18...,2028 2463 237 351 1791 21...
Soort vakantie: actief,4644 4271 2396 2128 2934 27...,7134 6487 3332 2917 3802 35...,55.3 51.0 18.9 15.9 36.4 35...,3455 3275 786 762 2670 25...
Soort vakantie: cultuur,1865 1943 741 831 1253 12...,2332 2470 883 1015 1450 14...,14.6 14.1 2.6 2.8 11.9 11...,1269 1248 188 242 1082 10...
Soort vakantie: eigen recreatieve accom.,1681 1709 1177 1181 597 6...,5232 4916 3943 3715 1290 12...,47.2 47.8 29.1 31.1 18.1 16...,895 923 369 396 526 5...
"Soort vakantie: familie, vrienden, e.d.",4544 3610 2838 2052 2205 18...,6363 5008 3646 2730 2717 22...,40.8 30.6 13.8 9.4 27.0 21...,2028 1707 564 448 1464 12...
Soort vakantie: natuur,2015 1946 1029 1039 1148 10...,2577 2479 1267 1282 1310 11...,25.1 23.0 8.2 8.4 16.9 14...,1487 1355 307 340 1180 10...
"Soort vakantie: overig, onbekend",3331 4445 1978 2853 1600 21...,4237 6197 2471 3701 1766 24...,30.4 46.2 12.2 20.3 18.3 25...,1795 2702 488 893 1307 18...
Soort vakantie: recreatie,1463 1360 991 819 540 5...,1742 1596 1144 910 599 6...,6.3 7.4 3.3 2.7 3.0 4...,507 582 232 201 275 3...
Soort vakantie: rondreis,1495 1618 . . 1418 15...,1683 1803 . . 1591 17...,28.6 30.8 . . 27.9 30...,3005 3130 . . 2963 31...
Soort vakantie: steden,3438 3449 1086 997 2721 27...,5112 4975 1346 1196 3766 37...,22.4 22.7 3.6 3.4 18.7 19...,2447 2519 259 271 2188 22...
Soort vakantie: strand,3922 3914 904 1043 3197 31...,4841 4924 1047 1191 3793 37...,52.9 52.5 6.7 7.0 46.2 45...,3748 3897 252 325 3496 35...
Totaal vakanties,14084 14124 8786 8855 10991 109...,41252 40854 19168 18738 22084 221...,323.6 326.1 99.2 102.0 224.5 224...,20637 21338 3486 3902 17151 174...
Vakantieduur: 16 of meer dagen,4897 4859 870 930 4133 40...,5697 5732 990 1073 4707 46...,139.0 141.1 29.4 32.5 109.7 108...,6942 7084 407 451 6535 66...
Vakantieduur: 2 tot 5 dagen (kort),7552 7511 5734 5596 3177 32...,15499 14839 10913 10336 4586 45...,32.6 31.3 21.9 20.8 10.7 10...,2812 3039 1369 1584 1443 14...
Vakantieduur: 5 of meer dagen (lang),12922 12961 5401 5423 10302 102...,25754 26015 8255 8401 17498 176...,291.1 294.8 77.3 81.1 213.8 213...,17825 18299 2117 2318 15707 159...
Vakantieduur: 5 tot 9 dagen,8093 8262 4113 4223 5033 51...,12552 12657 5657 5730 6894 69...,70.1 71.0 30.3 31.1 39.8 39...,5040 5291 1226 1368 3814 39...
Vakantieduur: 9 tot 16 dagen,6001 6025 1376 1316 4918 49...,7505 7625 1608 1598 5897 60...,81.9 82.6 17.6 17.6 64.3 65...,5842 5925 484 499 5358 54...
Vervoerwijze: auto,11152 11210 8093 8101 6393 64...,26920 26390 16865 16518 10055 98...,181.9 182.9 88.4 91.6 93.6 91...,7795 8085 3054 3417 4741 46...
Vervoerwijze: overige,1715 1598 791 739 1051 10...,2476 2436 1175 1136 1301 13...,19.2 18.7 6.8 6.7 12.4 12...,1080 1166 206 228 874 9...
Vervoerwijze: trein,1223 1221 767 761 533 5...,1742 1705 1112 1059 630 6...,7.1 7.3 3.9 3.4 3.2 3...,558 632 215 245 344 3...
Vervoerwijze: vliegtuig,6351 6490 . . 6351 64...,10114 10322 . . 10098 102...,115.4 117.2 . . 115.3 116...,11203 11455 . . 11192 114...

In [20]:
pivit_valakantie = nlvakanties.pivot_table(values=['Deelname/Totaal Nederlanders (x 1 000)'], 
                     index=['Bestemming en seizoen'], 
                     columns=['Vakantiekenmerken', 'Perioden'], 
                     aggfunc=np.sum,
                       )
pivit_valakantie

                               Deelname/Totaal Nederlanders (x 1 000)  \
Vakantiekenmerken                           Accommodatie: appartement
Perioden                                                        2017*
Bestemming en seizoen
Totaal vakanties                                                 2004
Vakantiebestemming: Nederland                                     260
Vakantiebestemming: buitenland                                   1794
Winterseizoen                                                     988
Zomerseizoen                                                     1203

                                                                            \
Vakantiekenmerken                        Accommodatie: hotel, pension, B&B
Perioden                           2018*                             2017*
Bestemming en seizoen
Totaal vakanties                    2065                              7642
Vakantiebestemming: Nederland        273                              3330
Vakantiebestemming: buitenland      1836                              5936
Winterseizoen                       1005                              4950
Zomerseizoen                        1218                              5200

                                                                        \
Vakantiekenmerken                        Accommodatie: kampeerverblijf
Perioden                           2018*                         2017*
Bestemming en seizoen
Totaal vakanties                    7770                          3064
Vakantiebestemming: Nederland       3217                          1694
Vakantiebestemming: buitenland      6059                          1925
Winterseizoen                       4670                           517
Zomerseizoen                        5594                          2954

                                                                         \
Vakantiekenmerken                        Accommodatie: overig, onbekend
Perioden                           2018*                          2017*
Bestemming en seizoen
Totaal vakanties                    3104                            965
Vakantiebestemming: Nederland       1756                            527
Vakantiebestemming: buitenland      1893                            467
Winterseizoen                        530                            460
Zomerseizoen                        2965                            624

                                                                           \
Vakantiekenmerken                        Accommodatie: particulier (alle)
Perioden                           2018*                            2017*
Bestemming en seizoen
Totaal vakanties                     893                             4017
Vakantiebestemming: Nederland        494                             1489
Vakantiebestemming: buitenland       431                             2793
Winterseizoen                        397                             2160
Zomerseizoen                         577                             2521

                                          ...                               \
Vakantiekenmerken                         ... Vakantieduur: 9 tot 16 dagen
Perioden                           2018*  ...                        2017*
Bestemming en seizoen                     ...
Totaal vakanties                    3942  ...                         6001
Vakantiebestemming: Nederland       1500  ...                         1376
Vakantiebestemming: buitenland      2767  ...                         4918
Winterseizoen                       2054  ...                         2076
Zomerseizoen                        2604  ...                         4595

                                                                       \
Vakantiekenmerken                        Vervoerwijze: auto
Perioden                           2018*              2017*     2018*
Bestemming en seizoen
Totaal vakanties                    6025              11152     11210
Vakantiebestemming: Nederland       1316               8093      8101
Vakantiebestemming: buitenland      4964               6393      6435
Winterseizoen                       1996               6924      6665
Zomerseizoen                        4749               9280      9431

                                                                 \
Vakantiekenmerken              Vervoerwijze: overige
Perioden                                        2017*     2018*
Bestemming en seizoen
Totaal vakanties                                 1715      1598
Vakantiebestemming: Nederland                     791       739
Vakantiebestemming: buitenland                   1051      1006
Winterseizoen                                     718       656
Zomerseizoen                                     1168      1143

                                                              \
Vakantiekenmerken              Vervoerwijze: trein
Perioden                                     2017*     2018*
Bestemming en seizoen
Totaal vakanties                              1223      1221
Vakantiebestemming: Nederland                  767       761
Vakantiebestemming: buitenland                 533       544
Winterseizoen                                  665       648
Zomerseizoen                                   713       706


Vakantiekenmerken              Vervoerwijze: vliegtuig
Perioden                                         2017*     2018*
Bestemming en seizoen
Totaal vakanties                                  6351      6490
Vakantiebestemming: Nederland                        .         .
Vakantiebestemming: buitenland                    6351      6490
Winterseizoen                                     3504      3303
Zomerseizoen                                      4541      4812

[5 rows x 76 columns]